ArchitectureMonuments/ArchitectureMonuments/Models/Model1.Designer.cs
// Создание кода T4 для модели "c:\users\gercog\documents\visual studio 2017\Projects\ArchitectureMonuments\ArchitectureMonuments\Models\Model1.edmx" включено. 
// Чтобы включить формирование кода прежних версий, измените значение свойства "Стратегия создания кода" конструктора
// на "Legacy ObjectContext". Это свойство доступно в окне "Свойства", если модель
// открыта в конструкторе.

// Если не сформированы контекст и классы сущности, возможная причина в том, что вы создали пустую модель, но
// еще не выбрали версию Entity Framework для использования. Чтобы сформировать класс контекста и классы сущностей
// для своей модели, откройте модель в конструкторе, щелкните правой кнопкой область конструктора и
// выберите "Обновить модель из базы данных", "Сформировать базу данных из модели" или "Добавить элемент формирования
// кода...".

ArchitectureMonuments/ArchitectureMonuments/Models/OtherFunction.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace OtherFunction
{
    public static class HelpFunction
    {
        public static string CropWord(this string inputString, int maxChars)
        {
            if (maxChars <= 0)
                throw new ArgumentOutOfRangeException("maxChars");
            if (inputString == null || inputString.Length < maxChars)
                return inputString;
            var lastSpaceIndex = inputString.LastIndexOf(" ", maxChars);
            var substringLength = (lastSpaceIndex > 0) ? lastSpaceIndex : maxChars;
            var truncatedString = inputString.Substring(0, substringLength).Trim() + "...";

            return truncatedString;
        }
    }
}

ArchitectureMonuments/ArchitectureMonuments/Controllers/MapController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ArchitectureMonuments.Controllers
{
    public class MapController : Controller
    {
        // GET: Map
        public ActionResult Index()
        {
            return View();
        }
    }
}

ArchitectureMonuments/ArchitectureMonuments/Controllers/MonumentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;



namespace ArchitectureMonuments.Controllers
{

   

    public class MonumentController : Controller
    {
        // GET: Monument
        private Models.MonumentDBEntities db= new Models.MonumentDBEntities();
        public ActionResult Index()
        {
            var all_items = db.Monuments.ToList<ArchitectureMonuments.Models.Monument>();
            var aall_items = all_items.OrderByDescending(x => x.likes).ToList<ArchitectureMonuments.Models.Monument>();
            List<ArchitectureMonuments.Models.Monument> items = new List<Models.Monument>();
            for (int i = 0; i < 3; i++)
            {
                items.Add(aall_items[i]);
            }
            return View(items);
        }

        public ActionResult MonumentView()
        {
            var items = db.Monuments;
            return View(items);
        }

        public ActionResult Details(int id)
        {
            var item = db.Monuments;
            var items = item.ToList<ArchitectureMonuments.Models.Monument>();
            ArchitectureMonuments.Models.Monument c = items.FirstOrDefault(com => com.Id == id);
            if (c != null)
                return PartialView(c);
            return HttpNotFound();
        }



       




    }
}

ArchitectureMonuments/ArchitectureMonuments/Views/Map/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="/maps/documentation/javascript/demos/demos.css">
    <style>
       
        #map {
            height: 800px;
            width: 900px;
        }
       
        
    </style>
</head>
<body>
   
    <div id="map"></div>
    <script>
        function initMap() {
            var map = new google.maps.Map(document.getElementById('map'), {
                zoom: 17,
                center: { lat: -34.397, lng: 150.644 }
            });
            var geocoder = new google.maps.Geocoder();

            
                geocodeAddress(geocoder, map);
           
        }

        function geocodeAddress(geocoder, resultsMap) {
            var address =  "проспект Свободи, 28,Lviv,Ukraine";
            geocoder.geocode({ 'address': address }, function (results, status) {
                if (status === 'OK') {
                    resultsMap.setCenter(results[0].geometry.location);
                   
                    var marker = new google.maps.Marker({
                        map: resultsMap,
                        position: results[0].geometry.location
                    });
                } else {
                    alert('Geocode was not successful for the following reason: ' + status);
                }
            });
        }
    </script>
    <script async defer
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCearFRazfBuhb5dLITBhnew4NPWueLDQw&v=3&callback=initMap">
    </script>

</body>
</html>

ArchitectureMonuments/ArchitectureMonuments/Views/MasterPage.cshtml
@model IEnumerable<ArchitectureMonuments.Models.Monument>
@{
    Layout = null;
}

<!DOCTYPE html>
<!--[if lt IE 7 ]><html class="ie ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!-->
<html lang="ru">
<!--<![endif]-->

<head>

    <meta charset="utf-8">

    <title>Заголовок</title>
    <meta name="description" content="">


    <!-- Header CSS (First Sections of Website: paste after release from _header.min.css here) -->
    <style></style>

    <!-- Load Main CSS Compilled without JS -->
        
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <link rel="stylesheet" href="~/Content/css/details.css">
    <link rel="stylesheet" href="~/Content/css/monuments.css">
    <link rel="stylesheet" href="~/Content/bootstrap.min.css">
    <link rel="stylesheet" href="~/Scripts/mapconfig.js" />
    <script src="~/Scripts/bootstrap.min.js"></script>

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    
    <link rel="shortcut icon" href="~/Contentimg/favicon/favicon.ico" type="image/x-icon">
    <link rel="apple-touch-icon" href="~/Contentimg/favicon/apple-touch-icon.png">
    <link rel="apple-touch-icon" sizes="72x72" href="~/Contentimg/favicon/apple-touch-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="114x114" href="~/Contentimg/favicon/apple-touch-icon-114x114.png">

</head>

<body>

    

        <div id="modDialog" class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true"  >
            <div class="modal-dialog modal-lg" style="width:1080px">
                <div id="dialogContent" class="modal-content" width="1080">
                    
                </div>
            </div>
        </div>
        <div class="container-fluid">
            <div class="row">
                <div class="background">
                    <div class="menu-line clearfix">
                        <div class="col-md-1">
                            <a href="#" class="logo"><img src="~/Content/img/logo.png" alt="logo"></a>
                        </div>
                        <div class="col-md-10 ">
                            <nav class="main-menu">
                                <ul>
                                    <li class"active"><a href="@Url.Action("Index","Monument")">головна</a></li>
                                    <li><a href="#">екскурсії</a></li>
                                    <li><a href="@Url.Action("MonumentView","Monument")">пам'ятки</a></li>
                                              
                                    <li><a href="#">допомога</a></li>
                                    <li><a href="#">інформація</a></li>
                                    <li><a href="#">контакти</a></li>
                                </ul>
                            </nav>
                        </div>
                    </div>
                    <div class="col-md-10 col-md-offset-1">
                        <div href="#" class="text">lviv architectural monuments</div>
                    </div>
                    <div class="col-md-8 col-md-offset-2">
                        <form class="searchthis" action="/search" method="get">
                            <input class="namanyay-search-box" name="q" size="40" type="text" placeholder="Введіть пам'ятку..." />
                            <input class="namanyay-search-btn" value="Пошук" type="submit" />
                        </form>
                    </div>
                    
                </div>
                @RenderBody()
            </div>
        </div>


  
    <div class="hidden"></div>

   


    <script type="text/javascript">

        $(function () {
            $.ajaxSetup({ cache: false });
            $(".compItem").click(function (e) {

                e.preventDefault();
                $.get(this.href, function (data) {
                    $('#dialogContent').html(data);
                    $('#modDialog').modal('show');
                });
            });
        })
    </script>
 
</body>
</html>

ArchitectureMonuments/ArchitectureMonuments/Views/Monument/Details.cshtml
@model ArchitectureMonuments.Models.Monument

<!--<div class="main-photo" style="background:url(@Model.main_photo_path)"><</div>-->
@{ 
    string newAddress = Model.adress.Substring(0, Model.adress.Length - 2) + ",Lviv,Ukraine";
}

<head>
    
    <style>
        #map {
            margin-top: 30px;
            width: 100%;
            height: 500px;
            border-radius: 10px;
        }
    </style>

    
   
</head>
<body>
    <img class="main-photo" src="@Model.main_photo_path" />
    <div class="modal-content">

        <div class="modal-header">
            <div class="row">
                <div class="col-md-6">
                    <div class="monument-name">@Model.name</div>
                </div>
                <div class="col-md-3 col-md-offset-2">
                    <div class="adress-line">
                        Адреса: <br />@Model.adress

                    </div>
                </div>
                <div class="col-md-1">
                    <div class="like-line"><img src="~/Content/img/like.svg" alt="like" width="30" height="30"><span class="numoflikes-line">@Model.likes</span></div>
                </div>
            </div>
        </div>

        <div class="modal-body">

            <div class="row">
                <div class="col-md-7">
                    <div class="description-line">@Model.description</div>
                    <div id="map"></div>
                </div>
                <div class="col-md-5 ">
                    <div class="comments">


                    </div>
                </div>

                
            </div>

            <div id="map"></div>
            <script type="text/javascript">
                function initMap() {
                    var map = new google.maps.Map(document.getElementById('map'), {
                        zoom: 17,
                        center: { lat: -34.397, lng: 150.644 }
                    });
                    var geocoder = new google.maps.Geocoder();


                    geocodeAddress(geocoder, map);

                }

                function geocodeAddress(geocoder, resultsMap) {

                    var address = "Наукова 21, Львів, Україна";
                    address = decodeURIComponent(address);
                    geocoder.geocode({ 'address': address }, function (results, status) {
                        if (status === 'OK') {
                            resultsMap.setCenter(results[0].geometry.location);

                            var marker = new google.maps.Marker({
                                map: resultsMap,
                                position: results[0].geometry.location
                            });
                        } else {
                            alert('Geocode was not successful for the following reason: ' + status);
                        }
                    });
                }
            </script>
            






            <!--@{
                 string[] images = Model.sub_photo_path.Split(new char[] { ' ' }, StringSplitOptions.RemoveEmptyEntries);
             }
             @foreach (var i in images)
             {
                 <img src="@i" width="570" height="400" /> <br />
             }
             -->

        </div>
        <script async defer
                src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCearFRazfBuhb5dLITBhnew4NPWueLDQw&v=3&callback=initMap">
        </script>

    </div>
</body>

ArchitectureMonuments/ArchitectureMonuments/Views/Monument/Index.cshtml
@model IEnumerable<ArchitectureMonuments.Models.Monument>
@{
    Layout = "/Views/MasterPage.cshtml";
    
}

<div class="rectangles">
    @{
        
        var tblTestList = Model.ToList();
        for (var i = 0; i < 1;i++ )

        {
            <div class="col-md-3 col-md-offset-2">
                <div class="rectangle">
                    <div class="circle1">
                        <a href="#" class="circlee1">
                            <img src="@tblTestList[i].main_photo_path" alt="circle" width="200" height="200">
                        </a>
                    </div>
                    <div class="name">@tblTestList[i].name</div>
                    <div class="opis">
                        <p>
                            @OtherFunction.HelpFunction.CropWord(tblTestList[i].description,100)
                            <br /><br />

                        @Html.ActionLink("Детальніше", "Details", new { id = tblTestList[i].Id }, new { @class = "compItem" })
                    </p>
                    </div>
                    <a href="#" class="like">
                        <img src="~/Content/img/like.svg" alt="like"><span class="numoflikes">@tblTestList[i].likes</span>
                    </a>
                </div>
            </div>
            <div class="col-md-3">
                <div class="rectangle">
                    <div class="circle1">
                        <a href="#" class="circlee1">
                            <img src="@tblTestList[i+1].main_photo_path" alt="circle" width="200" height="200">
                        </a>
                    </div>
                    <div class="name">@tblTestList[i + 1].name</div>
                    <div class="opis">
                        <p>
                            @OtherFunction.HelpFunction.CropWord(tblTestList[i+1].description, 100)<br /><br />

                        @Html.ActionLink("Детальніше", "Details", new { id = tblTestList[i+1].Id }, new { @class = "compItem" })
                    </p>
                    </div>
                    <a href="#" class="like">
                        <img src="~/Content/img/like.svg" alt="like"><span class="numoflikes">@tblTestList[i+1].likes</span>
                    </a>

                </div>

            </div>
                            <div class="col-md-3">
                                <div class="rectangle">
                                    <div class="circle1">
                                        <a href="#" class="circlee1">
                                            <img src="@tblTestList[i+2].main_photo_path" alt="circle" width="200" height="200">
                                        </a>
                                    </div>
                                    <div class="name">@tblTestList[i + 2].name</div>
                                    <div class="opis">
                                        <p>
                                            @OtherFunction.HelpFunction.CropWord(tblTestList[i+2].description, 100)<br /><br />

                                        @Html.ActionLink("Детальніше", "Details", new { id = tblTestList[i+2].Id }, new { @class = "compItem" })</p>
                                    
                                    </div>
                                    <a href="#" class="like">
                                        <img src="~/Content/img/like.svg" alt="like"><span class="numoflikes">@tblTestList[i+2].likes</span>
                                    </a>
                                </div>
                            </div>
                          
        }
    }
</div>
                
      

ArchitectureMonuments/ArchitectureMonuments/Views/Monument/MonumentView.cshtml
@model IEnumerable<ArchitectureMonuments.Models.Monument>
@{
    Layout = "/Views/MasterPage.cshtml";
}

<div class="rectangles">
    @{
        var tblTestList = Model.ToList();
        for (var i = 0; i < tblTestList.Count(); i += 5)

        {
            
            <div class="col-md-2 col-md-offset-1">
                <div class="rectangle">
                    <div class="circle1">
                        <a href="#" class="circlee1">
                            <img src="@tblTestList[i].main_photo_path" alt="circle" width="200" height="200">
                        </a>
                    </div>
                    <div class="name">@tblTestList[i].name</div>
                    <div class="opis">
                        <p>
                            @tblTestList[i].description.Remove(tblTestList[i].description.IndexOf('.'))...<br /><br />

                            @Html.ActionLink("Детальніше", "Details", new { id = tblTestList[i].Id }, new { @class = "compItem" })
                        </p>
                </div>
                    <a href="#" class="like">
                        <img src="~/Content/img/like.svg" alt="like"><span class="numoflikes">@tblTestList[i].likes</span>
                    </a>
            </div>
        </div>
                            <div class="col-md-2">
                                <div class="rectangle">
                                    <div class="circle1">
                                        <a href="#" class="circlee1">
                                            <img src="@tblTestList[i+1].main_photo_path" alt="circle" width="200" height="200">
                                        </a>
                                    </div>
                                    <div class="name">@tblTestList[i + 1].name</div>
                                    <div class="opis">
                                        <p>
                                            @tblTestList[i + 1].description.Remove(tblTestList[i + 1].description.IndexOf('.'))...<br /><br />

                                            @Html.ActionLink("Детальніше", "Details", new { id = tblTestList[i + 1].Id }, new { @class = "compItem" })
                                        </p>
                                    </div>
                                    <div class="likeposition">
                                        <a href="#" class="like">
                                            <img src="~/Content/img/like.svg" alt="like"><span class="numoflikes">@tblTestList[i + 1].likes</span>
                                        </a>
                                    </div>
                                </div>

                            </div>
                            <div class="col-md-2">
                                <div class="rectangle">
                                    <div class="circle1">
                                        <a href="#" class="circlee1">
                                            <img src="@tblTestList[i+2].main_photo_path" alt="circle" width="200" height="200">
                                        </a>
                                    </div>
                                    <div class="name">@tblTestList[i + 2].name</div>
                                    <div class="opis">
                                        <p>
                                            @tblTestList[i + 2].description.Remove(tblTestList[i + 2].description.IndexOf('.'))...<br /><br />

                                            @Html.ActionLink("Детальніше", "Details", new { id = tblTestList[i + 2].Id }, new { @class = "compItem" })
                                        </p>
                                    </div>
                                    <a href="#" class="like">
                                        <img src="~/Content/img/like.svg" alt="like"><span class="numoflikes">@tblTestList[i+2].likes</span>
                                    </a>
                                </div>
                            </div>
                            <div class="col-md-2">
                                <div class="rectangle">
                                    <div class="circle1">
                                        <a href="#" class="circlee1">
                                            <img src="@tblTestList[i+3].main_photo_path" alt="circle" width="200" height="200">
                                        </a>
                                    </div>
                                    <div class="name">@tblTestList[i + 3].name</div>
                                    <div class="opis">
                                        <p>
                                            @tblTestList[i + 3].description.Remove(tblTestList[i + 3].description.IndexOf('.'))...<br /><br />

                                            @Html.ActionLink("Детальніше", "Details", new { id = tblTestList[i + 3].Id }, new { @class = "compItem" })
                                        </p>
                                    </div>
                                    <a href="#" class="like">
                                        <img src="~/Content/img/like.svg" alt="like"><span class="numoflikes">@tblTestList[i+3].likes</span>
                                    </a>
                                </div>
                            </div>
                            <div class="col-md-2">
                                <div class="rectangle">
                                    <div class="circle1">
                                        <a href="#" class="circlee1">
                                            <img src="@tblTestList[i+4].main_photo_path" alt="circle" width="200" height="200">
                                        </a>
                                    </div>
                                    <div class="name">@tblTestList[i + 4].name</div>
                                    <div class="opis">
                                        <p>
                                            @tblTestList[i + 4].description.Remove(tblTestList[i + 4].description.IndexOf('.'))...<br /><br />

                                            @Html.ActionLink("Детальніше", "Details", new { id = tblTestList[i + 4].Id }, new { @class = "compItem" })
                                        </p>
                                    </div>
                                    <a href="#" class="like">
                                        <img src="~/Content/img/like.svg" alt="like"><span class="numoflikes">@tblTestList[i+4].likes</span>
                                    </a>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="space"></div>
                            </div>
        }
    }
</div>